# Generated by Django 4.1.3 on 2022-11-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conetent',
            new_name='content',
        ),
    ]
